// src/components/SynthesisResultModal.tsx
"use client";

import type { SynthesizeItineraryResult } from "@/lib/types";

export function SynthesisResultModal({
  open,
  loading,
  result,
  error,
  onClose,
  onOpenPlan,
}: {
  open: boolean;
  loading: boolean;
  result: SynthesizeItineraryResult | null;
  error: string | null;
  onClose: () => void;
  onOpenPlan: () => void;
}) {
  if (!open) return null;

  return (
    <>
      <div className="fixed inset-0 z-40 bg-ink/40 backdrop-blur-sm" onClick={onClose} />
      <div className="fixed inset-x-0 top-1/2 z-50 mx-auto w-[92%] max-w-lg -translate-y-1/2">
        <div className="thin-scroll max-h-[82vh] overflow-y-auto rounded-3xl border border-forest/15 bg-cream-50 p-6 shadow-lift">
          <div className="flex items-start justify-between gap-3">
            <div>
              <p className="eyebrow">Couples synthesis</p>
              <h2 className="font-display text-2xl font-semibold text-ink">One trip, for both of you</h2>
            </div>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close"
              className="flex h-9 w-9 items-center justify-center rounded-full border border-forest/15 bg-white/60 text-muted hover:text-forest"
            >
              ✕
            </button>
          </div>

          {loading && (
            <p className="mt-6 animate-pulse font-display text-lg text-muted">
              Reading both of your favorites and notes, finding the overlap…
            </p>
          )}

          {error && !loading && <p className="mt-6 text-sm text-clay">{error}</p>}

          {result && !loading && (
            <div className="mt-5 space-y-5">
              <div className="rounded-2xl border border-clay/30 bg-clay-100/40 p-4">
                <div className="flex items-center justify-between gap-2">
                  <h3 className="font-display text-xl font-semibold text-ink">{result.proposedPlan.title}</h3>
                  <span
                    className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${
                      result.source === "ai" ? "bg-forest text-cream" : "bg-forest/10 text-forest-600"
                    }`}
                    title={
                      result.source === "ai"
                        ? "Generated by the AI model"
                        : "Generated by the deterministic fallback"
                    }
                  >
                    {result.source === "ai" ? "AI" : "Fallback"}
                  </span>
                </div>
                <p className="mt-1 text-sm text-muted">{result.proposedPlan.route.join("  →  ")}</p>
                <p className="mt-2 text-sm leading-relaxed text-ink/85">{result.rationale}</p>
              </div>

              {result.overlapHighlights.length > 0 && (
                <div>
                  <p className="eyebrow mb-2">Where you both agreed</p>
                  <ul className="space-y-1.5">
                    {result.overlapHighlights.map((h, i) => (
                      <li key={i} className="flex gap-2 text-sm text-ink/85">
                        <span className="text-forest">♥</span>
                        <span>{h}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {result.tradeoffs.length > 0 && (
                <div>
                  <p className="eyebrow mb-2">Tradeoffs made</p>
                  <ul className="space-y-1.5">
                    {result.tradeoffs.map((t, i) => (
                      <li key={i} className="flex gap-2 text-sm text-ink/80">
                        <span className="text-clay">·</span>
                        <span>{t}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="flex flex-wrap gap-2 pt-1">
                <button type="button" onClick={onOpenPlan} className="btn btn-primary text-sm">
                  Open saved plan
                </button>
                <button type="button" onClick={onClose} className="btn btn-secondary text-sm">
                  Done
                </button>
              </div>
              <p className="text-xs text-muted">
                Saved as a new plan version. Your original plans are untouched.
              </p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
